import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Matt',
      email: 'admin@example.com',
      phoneno: '09152078490',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Deza',
      email: 'admin2@example.com',
      phoneno: '09152078490',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Ivan',
      email: 'admin3@example.com',
      phoneno: '09152078490',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Shiela',
      email: 'admin4@example.com',
      phoneno: '09152078490',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Marichu',
      email: 'admin5@example.com',
      phoneno: '09152078490',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Ivan',
      email: 'user@example.com',
      phoneno: '09152078490',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Birthday cake',
      slug: 'cake1',
      category: 'Cake',
      image: '/image/cake1.jpg',
      price: 650,
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description:
        'White Coated || Minimal Design of Icing || Minimal Color Design || Three Layer of Sponge Cakes || Cake Layer Filling ',
      isFeatured: true,
      banner: '/image/bn1.png',
    },
    {
      name: 'Redvelvet Cheese Cupcake',
      slug: 'cake2',
      category: 'Cupcake',
      image: '/image/capcake1.png',
      price: 250,
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description:
        '- cream cheese frosting || white chocolate on top || red powder || 6 pcs in 1 box',
      isFeatured: true,
      banner: '/image/bn2.png',
    },
    {
      name: 'Chocolate Moist Cake',
      slug: 'cake3',
      category: 'Cake',
      image: '/image/cake2.png',
      price: 650,
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description:
        'vanilla coated || crushed nut(top and botton) || cream on top choco layer filling || three layer of sponge cakes',
    },
    {
      name: 'Strawberry Cake',
      slug: 'cake4',
      category: 'Cake',
      image: '/image/cake3.png',
      price: 650,
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description:
        'strawberry cream coated || kisses (strawberry and choco) || icing on top (caramel and strawberry) || candy balls decoration || three layer of choco moist cakes || strawberry layer filling',
    },
    {
      name: 'Sunflower Cake',
      slug: 'cake5',
      category: 'Cake',
      image: '/image/cake4.png',
      price: 650,
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description:
        'icing on top sun flower design || kisses chocolate || icing rounded || mocha coated || mango layer filling || three layer of sponge cakes',
    },
    {
      name: 'Ube Cake',
      slug: 'cake6',
      category: 'Cake',
      image: '/image/Cake5.png',
      price: 650,
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description:
        'cream and white choco on top || candy balls decoration || violet cream coated(ube flavor) || ube layer filling || three layer of sponge cakes  ',
    },
    {
      name: 'Choco cupcake',
      slug: 'cake7',
      category: 'Cupcake',
      image: '/image/capcake2.png',
      price: 250,
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description:
        'marshmallow  || choco bars || icing on top(choco flavor) || choco moist cake || 6 pcs in 1 box',
    },
    {
      name: 'Chocolate Moist cupcake',
      slug: 'cake8',
      category: 'Cupcake',
      image: '/image/capcakes3.png',
      price: 250,
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description:
        'icing on top (any color) || candy balls decoration || choco moist cakes || 6 pcs in 1 box 	 ',
    },
  ],
};
export default data;
